twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # Salesforce Web-to-case form variables
    globals:
        site_url: 'https://webdev.crowncommercial.gov.uk'
        web_to_case_post_url: 'https://crowncommercial--PreProd.cs102.my.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8'
        web_to_case_orgid: '00D1j0000008aYA'
        web_to_case_record_type: '012b00000005NWC'
        web_to_case_debug_email: 'carlos@studio24.net'
        survey_link: 'https://crowncommercial.qualtrics.com/jfe/form/SV_b2hqVz3TYDCxN2u'
        cat_domain: 'https://dev-ccs-scale-cat-buyer-ui.london.cloudapps.digital'
        ppgLogin: 'https://dev.identify.crowncommercial.gov.uk/'
        ppgCreateAccount: 'https://dev.identify.crowncommercial.gov.uk/manage-org/register'
