content_types:
  page:
    api_endpoint: wp/v2/pages
    content_fields: pages.yaml
    source_content_type: page
    taxonomies:
      - pillars
      - sectors
  news:
    api_endpoint: wp/v2/posts
    content_fields: news.yaml
    source_content_type: post
    taxonomies:
      - categories
      - tags
  upcoming_deals:
    api_endpoint: ccs/v1/upcoming-deals
    content_fields: upcoming-deals.yaml
  frameworks:
    api_endpoint: ccs/v1/frameworks
    content_fields: frameworks.yaml
  framework_suppliers:
    api_endpoint: ccs/v1/framework-suppliers
    content_fields: framework-suppliers.yaml
  framework_lot_suppliers:
    api_endpoint: ccs/v1/lot-suppliers
    content_fields: framework-suppliers.yaml
  suppliers:
    api_endpoint: ccs/v1/suppliers
    content_fields: suppliers.yaml
  esourcing_dates:
    api_endpoint: ccs/v1/esourcing-dates
    content_fields: esourcing-dates.yaml
  whitepapers:
    api_endpoint: wp/v2/whitepaper
    content_fields: whitepapers.yaml
  webinars:
    api_endpoint: wp/v2/webinar
    content_fields: webinars.yaml
  digital_brochures:
    api_endpoint: wp/v2/digital_brochure
    content_fields: digital_brochures.yaml
  downloadable_resources:
    api_endpoint: wp/v2/downloadable
    content_fields: downloadable-resources.yaml
  events:
    api_endpoint: wp/v2/event
    content_fields: events.yaml
    source_content_type: event
  redirections:
    api_endpoint: ccs/v1/redirections
    content_fields: redirections.yaml
  glossary:
    api_endpoint: ccs/v1/glossary
    content_fields: glossary.yaml
  csc_message:
    api_endpoint: ccs/v1/csc-message
    content_fields: csc-message.yaml
  homepage_content:
    api_endpoint: ccs/v1/homepage-components
    content_fields: homepage-content.yaml
global:
  image_sizes:
    - thumbnail
    - medium
    - medium_large
    - large
    - full
    - news-size-s
    - news-size-m
    - news-size-l
    - news-size-xl
