type: flexible
components:
  intro_intro:
    intro_intro_heading:
      type: text
    intro_intro_content:
      type: richtext
    intro_intro_cta_label:
      type: text
    intro_intro_cta_destination:
      type: text
    intro_intro_secondary_label:
      type: text
    intro_intro_secondary_destination:
      type: text
    intro_intro_media:
      type: array
      content_fields:
        video_video_video:
          type: richtext
        image_image_image:
          type: image
        image_image_caption:
          type: richtext
        video_video_caption:
          type: richtext
    intro_intro_flip_media_text:
      type: text
  text_text:
    text_text_text:
      type: richtext
  subcategories_subcategories:
    subcategories_subcategories_optional_icon:
      type: image
    subcategories_subcategories_heading:
      type: text
    subcategories_subcategories_content:
      type: richtext
    subcategories_subcategories_links:
      type: array
      content_fields:
        link_link_heading:
          type: text
        link_link_content:
          type: richtext
        link_link_link_url:
          type: text
        link_link_link_text:
          type: text
  accordion_accordion:
    accordion_accordion_heading:
      type: text
    accordion_accordion_open_all_by_default:
      type: boolean
    accordion_accordion_introduction:
      type: richtext
    accordion_accordion_items:
      type: array
      content_fields:
        items_title:
          type: text
        items_content:
          type: richtext
  feature_news_feature_news:
    feature_news_feature_news_heading:
      type: text
    feature_news_feature_news_view_more_text:
      type: text
    articles:
      type: relation_array
      content_type:
        - news
      post_lead_text:
        type: text
    feature_news_feature_news_news_type:
      type: array
      content_fields:
        term_taxonomy_id:
          type: text
    feature_news_feature_news_products_and_services:
      type: array
      content_fields:
        term_taxonomy_id:
          type: text
    feature_news_feature_news_sectors:
      type: array
      content_fields:
        term_taxonomy_id:
          type: text
  feature_events_feature_events:
    feature_events_feature_events_heading:
      type: text
    articles:
      type: relation_array
      content_type:
        - events
  pillars_pillars:
    pillars_pillars_heading:
      type: text
    pillars_pillars_pillars:
      type: array
      content_fields:
        pillars_icon:
          type: image
        pillars_taxonomy:
          type: plainarray
        pillars_title:
          type: text
        pillars_content:
          type: richtext
  cards_cards:
    cards_cards_heading:
      type: text
    cards_cards_cards:
      type: array
      content_fields:
        cards_title:
          type: text
        cards_content:
          type: richtext
  sectors_sectors:
    sectors_sectors_heading:
      type: text
    sectors_sectors_sectors:
      type: array
      content_fields:
        sectors_taxonomy:
          type: plainarray
        sectors_title:
          type: text
        sectors_content:
          type: richtext
  quote_and_image_quote_and_image:
    quote_and_image_quote_and_image_image:
      type: image
    quote_and_image_quote_and_image_quote:
      type: richtext
    quote_and_image_quote_and_image_name:
      type: richtext
    quote_and_image_quote_and_image_job:
      type: richtext
  achievement_and_image_achievement_and_image:
    achievement_and_image_achievement_and_image_image:
      type: image
    achievement_and_image_achievement_and_image_text:
      type: richtext
  free_text_free_text:
    free_text_free_text_right_content_new:
      type: richtext
    free_text_free_text_left_content_new:
      type: richtext
    free_text_free_text_right_heading:
      type: richtext
    free_text_free_text_left_heading:
      type: richtext
    free_text_free_text_cta_label:
      type: text
    free_text_free_text_cta_destination:
      type: text
  featured_featured:
    featured_featured_section_heading:
      type: richtext
    featured_featured_heading_1:
      type: richtext
    featured_featured_heading_2:
      type: richtext
    featured_featured_heading_3:
      type: richtext
    featured_featured_body_1:
      type: richtext
    featured_featured_body_2:
      type: richtext
    featured_featured_body_3:
      type: richtext
    featured_featured_link_1_title:
      type: richtext
    featured_featured_link_2_title:
      type: richtext
    featured_featured_link_3_title:
      type: richtext
    featured_featured_link_1_destination:
      type: richtext
    featured_featured_link_2_destination:
      type: richtext
    featured_featured_link_3_destination:
      type: richtext
  tabs_tabs:
    tabs_tabs_heading:
      type: text
    tabs_tabs_tabs:
      type: array
      content_fields:
        tabs_title:
          type: text
        tabs_content:
          type: richtext

