rm_number:
  type: text
title:
  type: text
type:
  type: text
summary:
  type: richtext
description:
  type: richtext
updates:
  type: richtext
cas_updates:
  type: array
  content_fields:
    framework_cas_updates_date:
      type: date
    framework_cas_updates_update:
      type: richtext
benefits:
  type: richtext
how_to_buy:
  type: richtext
availability:
  type: richtext
cannot_use:
  type: richtext
terms:
  type: text
pillar:
  type: text
category:
  type: text
status:
  type: text
regulation_type:
  type: text
start_date:
  type: date
end_date:
  type: date
tenders_open_date:
  type: date
tenders_close_date:
  type: date
expected_live_date:
  type: date
expected_award_date:
  type: date
published_status:
  type: text
document_updates:
  type: richtext
customer_guide:
  type: richtext
core_terms_conditions:
  type: richtext
call_off_order_form:
  type: richtext
joint_schedules:
  type: array
  content_fields:
    joint_schedule_document_name:
      type: text
    joint_schedule_document:
      type: text
    joint_schedule_document_type:
      type: text
    joint_schedule_document_usage:
      type: text
    joint_schedule_document_description:
      type: richtext
    joint_schedule_file_size:
      type: number
call_off_schedules:
  type: array
  content_fields:
    call_off_schedule_document_name:
      type: text
    call_off_schedule_document:
      type: text
    call_off_schedule_document_type:
      type: text
    call_off_schedule_document_usage:
      type: text
    call_off_schedule_document_description:
      type: richtext
    call_off_schedule_file_size:
      type: number
framework_schedules:
  type: array
  content_fields:
    framework_schedule_document_name:
      type: text
    framework_schedule_document:
      type: text
    framework_schedule_document_usage:
      type: text
    framework_schedule_document_description:
      type: richtext
    framework_schedule_file_size:
      type: number
templates:
  type: richtext
lots:
  type: array
  content_fields:
    lot_number:
      type: text
    title:
      type: text
    status:
      type: text
    description:
      type: richtext
    expiry_date:
      type: date
    suppliers:
      type: array
      content_fields:
        name:
          type: text
        duns_number:
          type: text
        phone_number:
          type: text
        street:
          type: text
        city:
          type: text
        country:
          type: text
        postcode:
          type: text
        website:
          type: text
        trading_name:
          type: text
documents:
  type: array
  content_fields:
    title:
      type: text
    url:
      type: text
    file_size:
      type: number
total_suppliers:
  type: number
upcoming_deal_details:
  type: richtext
crp_compliant:
  type: boolean
